// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTiwTkltkVMth3CJFi47Jwvj3ebPvBcMU',
    appId: '1:11040427137:web:c34637b06bafd5934b5180',
    messagingSenderId: '11040427137',
    projectId: 'phone-auth-6c904',
    authDomain: 'phone-auth-6c904.firebaseapp.com',
    storageBucket: 'phone-auth-6c904.appspot.com',
    measurementId: 'G-7L4ZX5E0RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPl9X1OuYFlCvLfXrmy8CKEyUPi_J4e6Y',
    appId: '1:11040427137:android:d36b69140d84c1664b5180',
    messagingSenderId: '11040427137',
    projectId: 'phone-auth-6c904',
    storageBucket: 'phone-auth-6c904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PXC3cdukx0wM7NbxI1Fb61O5vKLvkjA',
    appId: '1:11040427137:ios:135d98dd73bccff64b5180',
    messagingSenderId: '11040427137',
    projectId: 'phone-auth-6c904',
    storageBucket: 'phone-auth-6c904.appspot.com',
    androidClientId: '11040427137-66mj30eiv2866sjlp85i7fhmuvvbk1pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.jopFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7PXC3cdukx0wM7NbxI1Fb61O5vKLvkjA',
    appId: '1:11040427137:ios:135d98dd73bccff64b5180',
    messagingSenderId: '11040427137',
    projectId: 'phone-auth-6c904',
    storageBucket: 'phone-auth-6c904.appspot.com',
    androidClientId: '11040427137-66mj30eiv2866sjlp85i7fhmuvvbk1pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.jopFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwCRu2a14kO_i0JYstB1GAYW0cjfn-pM4',
    appId: '1:11040427137:web:5e1878e2e94786a14b5180',
    messagingSenderId: '11040427137',
    projectId: 'phone-auth-6c904',
    authDomain: 'phone-auth-6c904.firebaseapp.com',
    storageBucket: 'phone-auth-6c904.appspot.com',
    measurementId: 'G-Z8NNJXC9SD',
  );
}
